name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  # Scheduled trigger checks for breakage caused by changes to external resources (libraries, platforms)
  schedule:
    # run every Saturday at 3 AM UTC
    - cron: "0 3 * * 6"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:avr:uno

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # Install library dependencies.
          sketch-paths: |
            # Sketches to compile
            - ./examples/Motion-Control-II/01_Step_Check
            - ./examples/Motion-Control-II/02_Step_Control
            - ./examples/Motion-Control-II/03_Direction_Control
            - ./examples/Motion-Control-II/04_Speed_Control
            - ./examples/Multi-Motor/01_Check_Inputs_Two_Axis
            - ./examples/Multi-Motor/02_Manual_Control_Two_Axis
            - ./examples/Multi-Motor/03_toStepXY_Two_Axis
            - ./examples/Multi-Motor/04_toPositionXY_Two_Axis
            - ./examples/Multi-Motor/05_Draw_Lines
            - ./examples/Multi-Motor/06_Draw_Rectangle
            - ./examples/Multi-Motor/07_Draw_Circle
            - ./examples/Single-Motor/01_Check_Inputs
            - ./examples/Single-Motor/02_Homing_procedure
            - ./examples/Single-Motor/03_Move_To_Step
            - ./examples/Single-Motor/04_Move_To_Position
            - ./examples/Single-Motor/05_Ultrasonic_Sensor

          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
